SET curdir=%~dp0
DEL /s /q "%curdir%\binmodules\example\obj"
DEL /s /q "%curdir%\binmodules\luasocket\obj"
DEL /s /q "%curdir%\contrib\curl\bin"
DEL /s /q "%curdir%\contrib\curl\obj"
DEL /s /q "%curdir%\contrib\libzip\obj"
DEL /s /q "%curdir%\contrib\libzip\bin"
DEL /s /q "%curdir%\contrib\lua\obj"
DEL /s /q "%curdir%\contrib\lua\bin"
DEL /s /q "%curdir%\contrib\luashim\obj"
DEL /s /q "%curdir%\contrib\luashim\bin"
DEL /s /q "%curdir%\contrib\mbedtls\obj"
DEL /s /q "%curdir%\contrib\mbedtls\bin"
DEL /s /q "%curdir%\contrib\zlib\obj"
DEL /s /q "%curdir%\contrib\zlib\bin"